name: CI - Test clean utility

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build clean
        run: make

      - name: Test clean with bad_data.txt
        run: ./clean < bad_data.txt > cleaned_data.txt

      - name: upload cleaned bad_data.txt
        uses: actions/upload-artifact@v4
        with:
          name: cleaned_data.txt upload
          path: ./cleaned_data.txt

      - name: Test clean with bad_data2.txt
        run: ./clean < bad_data2.txt > cleaned_data2.txt

      - name: upload cleaned bad_data2.txt
        uses: actions/upload-artifact@v4
        with:
          name: cleaned_data2.txt upload
          path: ./cleaned_data2.txt

      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: clean
          path: ./clean